source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/DLinkSDK/deeplink-dev-specs.git'


platform :ios, '12.0'

target 'FeatureDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FeatureDemo
    pod 'FeatureExtract'
end
